spring.application.name=spring

# PostgreSQL接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

# テーブル自動生成
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always

#Time_Zone
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Tokyo