spring.application.name=spring

# PostgreSQL接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword

# テーブル自動生成
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2の設定は削除（PostgreSQLを使うので不要）
# spring.h2.console.enabled=true